# Generated by Django 3.2.3 on 2021-05-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_drink'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_categories',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='products_drinks',
        ),
    ]
