# Generated by Django 3.2.3 on 2021-05-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210523_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='products_drink',
        ),
    ]
