# Generated by Django 3.2.3 on 2021-05-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allergy_allergydrink_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergydrink',
            name='name',
        ),
        migrations.AddField(
            model_name='allergydrink',
            name='drink',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
    ]
