# Generated by Django 3.2.3 on 2021-05-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210523_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergydrink',
            table='products_allergydrink',
        ),
    ]
